version: '3.8'

services:
  db:
    image: postgres:12
    container_name: bkauto-db
    restart: always
    ports:
      - "5433:5432"
    volumes:
      # Map the named volume 'bkauto' to the PostgreSQL data directory
      - bkauto:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PlLcIne8Syc9e28KSioAeA/Vzz8=
    healthcheck:
      # Check if PostgreSQL server is accepting connections
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  backend:
    container_name: bkauto-be
    build:
      context: ./bkauto-be/Demo
      dockerfile: Dockerfile.be
    restart: always
    ports:
      - "6066:6066"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./application.deploy.yml:/config/application.yml
    depends_on:
      db:
        condition: service_healthy # Wait for db to be healthy
    # Optional: Adjust healthcheck command based on your backend's health endpoint
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6066/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  frontend:
    container_name: bkauto-fe
    build:
      context: .
      dockerfile: Dockerfile.fe
    restart: always
    volumes:
      - ./constants.js:/frontend/src/composables/constants.js
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  # Define the named volume for database persistence
  bkauto: {}